# yapf: disable
quotes = [
    "style is the answer to everything.",
    "to do a dull thing with style is preferable to doing a dangerous thing without it.",
    "to do a dangerous thing with style is what i call art.",
    "five is right out.",
    "you must construct additional pylons.",
    "don't panic.",
    "so long, and thanks for all the fish.",
    "show life the flyest version of you.",
    "let's dance again, shall we?",
    "the sharif don't like it.",
    "un-re-route the rivers.",
    "pleased to meet you. hope you guessed my name.",
    "and don'tcha come back no more.",
    "egal wer kommt, egal wer geht, egal, das kommt nicht darauf an.",
    "nobody expects the spanish inquisition!",
    "on the internet, nobody knows you're a dog.",
    "give me ASCII or give me deaþ!",
    "as seen on tv!",
    "removed herobrine.",
    "error: could not load quote.",
    "gotta get down on friday.",
    "and plummeted sixteen feet through an announcer's table."
]
