# yapf: disable
quotes = [
    "style is the answer to everything.",
    "to do a dull thing with style is preferable to doing a dangerous thing without it.",
    "to do a dangerous thing with style is what i call art.",
    "five is right out.",
    "you must construct additional pylons.",
    "don't panic.",
    "so long, and thanks for all the fish.",
    "show life the flyest version of you.",
    "let's dance again, shall we?",
    "the sharif don't like it.",
    "un-re-route the rivers.",
    "pleased to meet you. hope you guessed my name.",
    "and don'tcha come back no more.",
    "egal wer kommt, egal wer geht, egal, das kommt nicht darauf an.",
    "nobody expects the spanish inquisition!",
    "on the internet, nobody knows you're a dog.",
    "give me ASCII or give me deaþ!",
    "as seen on tv!",
    "removed herobrine.",
    "error: could not load quote.",
    "gotta get down on friday.",
    "and plummeted sixteen feet through an announcer's table.",
    "hi, mum.",
    "thanks, 4censord.",
    "thanks, isaac.",
    "be water, my friend.",
    "ahora todo va.",
    "siamo tutti antifascisti.",
    "the revolution will not be televised.",
    "don't be shocked by the tone of my voice.",
    "walk without rhythm. it won't attract the worm.",
    "and instead i pour the milk.",
    "el estado opresor es un macho violador.",
    "there is a house in new orleans.",
    "keine sorge, mama, ganz normal, so wollt dein sohn doch leben.",
    "oh, my love, my lover. i belong to you.",
    "letting the days go by.",
    "and you may ask yourself: how did i get here?",
    "lady, i just feel like i won't get you out of my mind.",
    "aber ich will dein fahrradsattel sein.",
    "it rains, it pours.",
    "nein mann, ich will noch nicht gehen. ich will noch'n bisschen tanzen.",
    "power to the people that struggle every day.",
    "back once again for the renegade master.",
    "tooting the boris, smoking on the rishi.",
    "my, my! i think we have a spy!",
    "bamboleo.",
    "all the old paintings on the tomb, they do the sun dance, don'tcha know?",
    "it's the london to brighton line.",
    "drive that funky soul.",
    "tea. earl gray. hot.",
    "there is no try.",
    "that's no moon.",
    "everything not saved will be lost.",
    "let me guess. someone stole your sweetroll?",
    "dragons were never gone. they were just invisible and very, very quiet.",
    "werebears? where? bears?",
    "snow falls. why worry where it goes?",
    "the history of all hitherto existing society is the history of class struggles.",
    "i am fond of pigs.",
    "we ought to make the pie higher.",
    "she take me money and run venezuela.",
    "sixteen tons, and whaddaya get? another day older, and deeper in debt.",
]
